# Site Settings
baseurl: ""
url : "https://swapnilshrikhande.in"

# Blog Settings
theme_settings :
  title : Personal Blog
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/avatar.png
    username : Swapnil Shrikhande
    description : Developer
    experience :
      - start : 2020 Jul
        end : Current
        experience : Madaket Health, Technical Lead    
      - start : 2012 Dec
        end : 2020 Jun
        experience : Eternus Solutions, Senior Technical Lead    
      - start : 2011 Jan
        end : 2012 Dec
        experience : Kan Biosys, Software Developer    
      - start : 2009 May
        end : 2011 Jan
        experience : Consistent Technologies, Java Developer
    skills : 
      - skill : HTML5 & CSS
        value : 40  # Percent value
      - skill : JavaScript
        value : 30  # Percent value  
        
  # Icons
  icons :
    email:  # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: swapnilshrikhande
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: swapnilshrkhnde
    youtube: 
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
